// 由 mc-local-share generate_ts 自动生成，请勿手改。

import { MessageControllerBase } from '../MessageControllerBase';
import { MESSAGE_ID } from 'mc-local-share';
import { NetMsg_AchieveInfo_CN } from './NetMsg_AchieveInfo_CN';
import { NetMsg_AchieveInfo_SN } from './NetMsg_AchieveInfo_SN';
import { NetMsg_AchieveReward_CS } from './NetMsg_AchieveReward_CS';
import { NetMsg_ActivityEventData_PUSH } from './NetMsg_ActivityEventData_PUSH';
import { NetMsg_ActivityGetReward_CS } from './NetMsg_ActivityGetReward_CS';
import { NetMsg_ActivityGetTradeReward_CS } from './NetMsg_ActivityGetTradeReward_CS';
import { NetMsg_ActivityInfo_CS } from './NetMsg_ActivityInfo_CS';
import { NetMsg_ActivityInfoRep_SN } from './NetMsg_ActivityInfoRep_SN';
import { NetMsg_ActivityInfoReq_CN } from './NetMsg_ActivityInfoReq_CN';
import { NetMsg_ActivityRMBBuy_PUSH } from './NetMsg_ActivityRMBBuy_PUSH';
import { NetMsg_ArenaBattleComplete } from './NetMsg_ArenaBattleComplete';
import { NetMsg_ArenaBuyTicket } from './NetMsg_ArenaBuyTicket';
import { NetMsg_ArenaEnterRep } from './NetMsg_ArenaEnterRep';
import { NetMsg_ArenaEnterReq } from './NetMsg_ArenaEnterReq';
import { NetMsg_ArenaGiveUp } from './NetMsg_ArenaGiveUp';
import { NetMsg_ArenaReward } from './NetMsg_ArenaReward';
import { NetMsg_ArenaSelCard } from './NetMsg_ArenaSelCard';
import { NetMsg_ArenaSelHero } from './NetMsg_ArenaSelHero';
import { NetMsg_BattleAutoFight_CS } from './NetMsg_BattleAutoFight_CS';
import { NetMsg_BattleCommonError } from './NetMsg_BattleCommonError';
import { NetMsg_BattleEmoji_CN } from './NetMsg_BattleEmoji_CN';
import { NetMsg_BattleEmoji_SN } from './NetMsg_BattleEmoji_SN';
import { NetMsg_BattleGetEmojiList_CS } from './NetMsg_BattleGetEmojiList_CS';
import { NetMsg_BattleQuit_CN } from './NetMsg_BattleQuit_CN';
import { NetMsg_BattleReady_CN } from './NetMsg_BattleReady_CN';
import { NetMsg_BattleWaiting_SN } from './NetMsg_BattleWaiting_SN';
import { NetMsg_BPActive } from './NetMsg_BPActive';
import { NetMsg_BPBuyLevel } from './NetMsg_BPBuyLevel';
import { NetMsg_BPInfoRec } from './NetMsg_BPInfoRec';
import { NetMsg_BPInfoReq } from './NetMsg_BPInfoReq';
import { NetMsg_BPLevelReward } from './NetMsg_BPLevelReward';
import { NetMsg_Buy_PVE } from './NetMsg_Buy_PVE';
import { NetMsg_CancelMatch_CS } from './NetMsg_CancelMatch_CS';
import { NetMsg_CardCompound } from './NetMsg_CardCompound';
import { NetMsg_CardResolve } from './NetMsg_CardResolve';
import { NetMsg_ChallengeHero } from './NetMsg_ChallengeHero';
import { NetMsg_ChallengeHero_CN } from './NetMsg_ChallengeHero_CN';
import { NetMsg_ChallengeHeroComplete } from './NetMsg_ChallengeHeroComplete';
import { NetMsg_ChampBattleComplete_SN } from './NetMsg_ChampBattleComplete_SN';
import { NetMsg_ChampBuyTicket_CS } from './NetMsg_ChampBuyTicket_CS';
import { NetMsg_ChampDeleteDeck_CS } from './NetMsg_ChampDeleteDeck_CS';
import { NetMsg_ChampEditDeck_CS } from './NetMsg_ChampEditDeck_CS';
import { NetMsg_ChampGetInfo_CS } from './NetMsg_ChampGetInfo_CS';
import { NetMsg_ChampGetMatchReward_CS } from './NetMsg_ChampGetMatchReward_CS';
import { NetMsg_ChampGetResultReward_CS } from './NetMsg_ChampGetResultReward_CS';
import { NetMsg_ChangeDeckCardBack } from './NetMsg_ChangeDeckCardBack';
import { NetMsg_ChangeDefaultCardBack } from './NetMsg_ChangeDefaultCardBack';
import { NetMsg_ChangePlayerName } from './NetMsg_ChangePlayerName';
import { NetMsg_ChatInfo_CN } from './NetMsg_ChatInfo_CN';
import { NetMsg_ChatInfo_SN } from './NetMsg_ChatInfo_SN';
import { NetMsg_ClearExpression_CS } from './NetMsg_ClearExpression_CS';
import { NetMsg_Cook } from './NetMsg_Cook';
import { NetMsg_CreatePVERoom_CN } from './NetMsg_CreatePVERoom_CN';
import { NetMsg_CreatePVERoom_SN } from './NetMsg_CreatePVERoom_SN';
import { NetMsg_DailySignIn } from './NetMsg_DailySignIn';
import { NetMsg_DailySignIn_CN } from './NetMsg_DailySignIn_CN';
import { NetMsg_DailySignIn_SN } from './NetMsg_DailySignIn_SN';
import { NetMsg_DeleteDeck } from './NetMsg_DeleteDeck';
import { NetMsg_DLC4Forging } from './NetMsg_DLC4Forging';
import { NetMsg_DLC4GetInfo } from './NetMsg_DLC4GetInfo';
import { NetMsg_DLC4SetEquiment } from './NetMsg_DLC4SetEquiment';
import { NetMsg_DLC4SetTAlent } from './NetMsg_DLC4SetTAlent';
import { NetMsg_EditDeck } from './NetMsg_EditDeck';
import { NetMsg_EnterGame } from './NetMsg_EnterGame';
import { NetMsg_FirstPayPush } from './NetMsg_FirstPayPush';
import { NetMsg_FirstPayReward } from './NetMsg_FirstPayReward';
import { NetMsg_FixPay_CN } from './NetMsg_FixPay_CN';
import { NetMsg_FixPay_SN } from './NetMsg_FixPay_SN';
import { NetMsg_FriendBehavior_CN } from './NetMsg_FriendBehavior_CN';
import { NetMsg_FriendBehavior_SN } from './NetMsg_FriendBehavior_SN';
import { NetMsg_FriendCancelMatch_SN } from './NetMsg_FriendCancelMatch_SN';
import { NetMsg_FriendInfo_CN } from './NetMsg_FriendInfo_CN';
import { NetMsg_FriendInfo_SN } from './NetMsg_FriendInfo_SN';
import { NetMsg_FriendRefresh_SN } from './NetMsg_FriendRefresh_SN';
import { NetMsg_FriendRefreshScenes_CN } from './NetMsg_FriendRefreshScenes_CN';
import { NetMsg_FriendState_SN } from './NetMsg_FriendState_SN';
import { NetMsg_GetBattleResult } from './NetMsg_GetBattleResult';
import { NetMsg_GetDeckCode } from './NetMsg_GetDeckCode';
import { NetMsg_GetDeckData } from './NetMsg_GetDeckData';
import { NetMsg_GetFavorReward } from './NetMsg_GetFavorReward';
import { NetMsg_GetGiftInfo_CN } from './NetMsg_GetGiftInfo_CN';
import { NetMsg_GetGiftInfo_SN } from './NetMsg_GetGiftInfo_SN';
import { NetMsg_GetLoginActivityDataRep } from './NetMsg_GetLoginActivityDataRep';
import { NetMsg_GetLoginActivityDataReq } from './NetMsg_GetLoginActivityDataReq';
import { NetMsg_GetLoginActivityRewardRep } from './NetMsg_GetLoginActivityRewardRep';
import { NetMsg_GetLoginActivityRewardReq } from './NetMsg_GetLoginActivityRewardReq';
import { NetMsg_GetQuestion } from './NetMsg_GetQuestion';
import { NetMsg_GetRankDetailRep } from './NetMsg_GetRankDetailRep';
import { NetMsg_GetRankDetailReq } from './NetMsg_GetRankDetailReq';
import { NetMsg_GetRecordByID } from './NetMsg_GetRecordByID';
import { NetMsg_GetRecordInfo } from './NetMsg_GetRecordInfo';
import { NetMsg_GetRnakRep } from './NetMsg_GetRnakRep';
import { NetMsg_GetRnakReq } from './NetMsg_GetRnakReq';
import { NetMsg_GetShareDecks_CN } from './NetMsg_GetShareDecks_CN';
import { NetMsg_GetShareDecks_SN } from './NetMsg_GetShareDecks_SN';
import { NetMsg_GetShopInfo } from './NetMsg_GetShopInfo';
import { NetMsg_GetSignInInfo_CN } from './NetMsg_GetSignInInfo_CN';
import { NetMsg_GetSignInInfo_SN } from './NetMsg_GetSignInInfo_SN';
import { NetMsg_GildingRep } from './NetMsg_GildingRep';
import { NetMsg_GildingReq } from './NetMsg_GildingReq';
import { NetMsg_GildingResetRep } from './NetMsg_GildingResetRep';
import { NetMsg_GildingResetReq } from './NetMsg_GildingResetReq';
import { NetMsg_GMMain } from './NetMsg_GMMain';
import { NetMsg_GuideRecord } from './NetMsg_GuideRecord';
import { NetMsg_GuideRecordRep } from './NetMsg_GuideRecordRep';
import { NetMsg_Heartbeat_CN } from './NetMsg_Heartbeat_CN';
import { NetMsg_Heartbeat_SN } from './NetMsg_Heartbeat_SN';
import { NetMsg_HeroGiveGift } from './NetMsg_HeroGiveGift';
import { NetMsg_InfiBuyClue } from './NetMsg_InfiBuyClue';
import { NetMsg_InfiEnterRep } from './NetMsg_InfiEnterRep';
import { NetMsg_InfiEnterReq } from './NetMsg_InfiEnterReq';
import { NetMsg_InfiEventUnlock } from './NetMsg_InfiEventUnlock';
import { NetMsg_InfiEventUnlockRMBPush } from './NetMsg_InfiEventUnlockRMBPush';
import { NetMsg_InfiExitStage } from './NetMsg_InfiExitStage';
import { NetMsg_InfiGetSimpleDataRep } from './NetMsg_InfiGetSimpleDataRep';
import { NetMsg_InfiGetSimpleDataReq } from './NetMsg_InfiGetSimpleDataReq';
import { NetMsg_InfiGetStaticDataRep } from './NetMsg_InfiGetStaticDataRep';
import { NetMsg_InfiGetStaticDataReq } from './NetMsg_InfiGetStaticDataReq';
import { NetMsg_InfiGetStory } from './NetMsg_InfiGetStory';
import { NetMsg_InfiPushBattleComplete } from './NetMsg_InfiPushBattleComplete';
import { NetMsg_InfiPushStateChange } from './NetMsg_InfiPushStateChange';
import { NetMsg_InfiRecover } from './NetMsg_InfiRecover';
import { NetMsg_InfiRemoveCard } from './NetMsg_InfiRemoveCard';
import { NetMsg_InfiRemoveTreasure } from './NetMsg_InfiRemoveTreasure';
import { NetMsg_InfiRoundEndPush } from './NetMsg_InfiRoundEndPush';
import { NetMsg_InfiSelBattleReward } from './NetMsg_InfiSelBattleReward';
import { NetMsg_InfiSelClass } from './NetMsg_InfiSelClass';
import { NetMsg_InfiSelDifficulty } from './NetMsg_InfiSelDifficulty';
import { NetMsg_InfiSelectDeck } from './NetMsg_InfiSelectDeck';
import { NetMsg_InfiSelectHero } from './NetMsg_InfiSelectHero';
import { NetMsg_InfiSelectStage_CN } from './NetMsg_InfiSelectStage_CN';
import { NetMsg_InfiSelectStage_SN } from './NetMsg_InfiSelectStage_SN';
import { NetMsg_InfiSelEvent } from './NetMsg_InfiSelEvent';
import { NetMsg_InfiShopBuyItem } from './NetMsg_InfiShopBuyItem';
import { NetMsg_InfiStartShopBuyItem } from './NetMsg_InfiStartShopBuyItem';
import { NetMsg_InfiStartShopExit } from './NetMsg_InfiStartShopExit';
import { NetMsg_InfiStartShopRefresh } from './NetMsg_InfiStartShopRefresh';
import { NetMsg_InfiTakeChest } from './NetMsg_InfiTakeChest';
import { NetMsg_InfiUnlockDifficulty } from './NetMsg_InfiUnlockDifficulty';
import { NetMsg_InfiUpCard } from './NetMsg_InfiUpCard';
import { NetMsg_LeveUp } from './NetMsg_LeveUp';
import { NetMsg_MainTownReconnect } from './NetMsg_MainTownReconnect';
import { NetMsg_MissionBoxReward } from './NetMsg_MissionBoxReward';
import { NetMsg_MissionInfoRec } from './NetMsg_MissionInfoRec';
import { NetMsg_MissionInfoReq } from './NetMsg_MissionInfoReq';
import { NetMsg_MissionReward } from './NetMsg_MissionReward';
import { NetMsg_ModifyEquip } from './NetMsg_ModifyEquip';
import { NetMsg_NoticePush } from './NetMsg_NoticePush';
import { NetMsg_Pay_SN } from './NetMsg_Pay_SN';
import { NetMsg_Ping_CN } from './NetMsg_Ping_CN';
import { NetMsg_Ping_SN } from './NetMsg_Ping_SN';
import { NetMsg_PullActAccept } from './NetMsg_PullActAccept';
import { NetMsg_PullActInfo } from './NetMsg_PullActInfo';
import { NetMsg_PullActRewardReq } from './NetMsg_PullActRewardReq';
import { NetMsg_PushHeroInfo } from './NetMsg_PushHeroInfo';
import { NetMsg_PushLadderComplete } from './NetMsg_PushLadderComplete';
import { NetMsg_PushNotice_SN } from './NetMsg_PushNotice_SN';
import { NetMsg_PushPrizeInfo } from './NetMsg_PushPrizeInfo';
import { NetMsg_PVEActivityInfo } from './NetMsg_PVEActivityInfo';
import { NetMsg_PVECompletePush } from './NetMsg_PVECompletePush';
import { NetMsg_PVEDailyInfoRep } from './NetMsg_PVEDailyInfoRep';
import { NetMsg_PVEDailyInfoReq } from './NetMsg_PVEDailyInfoReq';
import { NetMsg_QueryExpressionInfo_CS } from './NetMsg_QueryExpressionInfo_CS';
import { NetMsg_QueryFriendInfo } from './NetMsg_QueryFriendInfo';
import { NetMsg_QueryPersonInfoReq } from './NetMsg_QueryPersonInfoReq';
import { NetMsg_QueryPersonInfoRsp } from './NetMsg_QueryPersonInfoRsp';
import { NetMsg_QueryUserTitelInfo_CN } from './NetMsg_QueryUserTitelInfo_CN';
import { NetMsg_QueryUserTitelInfo_SN } from './NetMsg_QueryUserTitelInfo_SN';
import { NetMsg_ReceiveGift } from './NetMsg_ReceiveGift';
import { NetMsg_RecordCollect } from './NetMsg_RecordCollect';
import { NetMsg_RecordDelete } from './NetMsg_RecordDelete';
import { NetMsg_RecordPlay } from './NetMsg_RecordPlay';
import { NetMsg_RidingLanternNotice_SN } from './NetMsg_RidingLanternNotice_SN';
import { NetMsg_RMB_PVE_SN } from './NetMsg_RMB_PVE_SN';
import { NetMsg_RMB_ShopBuy_SN } from './NetMsg_RMB_ShopBuy_SN';
import { NetMsg_SeasonRewardRep } from './NetMsg_SeasonRewardRep';
import { NetMsg_SeasonRewardReq } from './NetMsg_SeasonRewardReq';
import { NetMsg_SetDefaultExpression_CS } from './NetMsg_SetDefaultExpression_CS';
import { NetMsg_SetExpression_CS } from './NetMsg_SetExpression_CS';
import { NetMsg_SetHeadInfo_CN } from './NetMsg_SetHeadInfo_CN';
import { NetMsg_SetHeadInfo_SN } from './NetMsg_SetHeadInfo_SN';
import { NetMsg_SetHeadPicExReq } from './NetMsg_SetHeadPicExReq';
import { NetMsg_SetHeadPicExRsp } from './NetMsg_SetHeadPicExRsp';
import { NetMsg_SetHeadPicReq } from './NetMsg_SetHeadPicReq';
import { NetMsg_SetHeadPicRsp } from './NetMsg_SetHeadPicRsp';
import { NetMsg_SetHeroSkin } from './NetMsg_SetHeroSkin';
import { NetMsg_SetPlayerNameReq } from './NetMsg_SetPlayerNameReq';
import { NetMsg_SetUserTitle } from './NetMsg_SetUserTitle';
import { NetMsg_ShareDeck } from './NetMsg_ShareDeck';
import { NetMsg_ShopBuy } from './NetMsg_ShopBuy';
import { NetMsg_StartMatchArena_CS } from './NetMsg_StartMatchArena_CS';
import { NetMsg_StartMatchChamp_CS } from './NetMsg_StartMatchChamp_CS';
import { NetMsg_StartMatchPVP_CS } from './NetMsg_StartMatchPVP_CS';
import { NetMsg_Timeout_SN } from './NetMsg_Timeout_SN';
import { NetMsg_TransChatInfo_CN } from './NetMsg_TransChatInfo_CN';
import { NetMsg_TransChatInfo_SN } from './NetMsg_TransChatInfo_SN';
import { NetMsg_TrialSectionReward_CS } from './NetMsg_TrialSectionReward_CS';
import { NetMsg_UnloadExpressionShortcut_CS } from './NetMsg_UnloadExpressionShortcut_CS';
import { NetMsg_UpdateQuestion } from './NetMsg_UpdateQuestion';
import { NetMsg_UseItem } from './NetMsg_UseItem';
import { NetMsg_UseSharedDeck_NT } from './NetMsg_UseSharedDeck_NT';
import { NetMsg_UseSkinReq } from './NetMsg_UseSkinReq';
import { NetMsg_UseSkinRsp } from './NetMsg_UseSkinRsp';

export class MessageController extends MessageControllerBase {
  constructor() {
    super();
    this.AutoResponser[MESSAGE_ID.GET_ACHIEVE_INFO_REQ] = new NetMsg_AchieveInfo_CN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_AchieveInfo_SN();
    this.AutoResponser[MESSAGE_ID.GET_ACHIEVE_REWARD_REQ] = new NetMsg_AchieveReward_CS();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_ActivityEventData_PUSH();
    this.AutoResponser[MESSAGE_ID.GET_ACTIVITY_REWARD_REQ] = new NetMsg_ActivityGetReward_CS();
    this.AutoResponser[MESSAGE_ID.GET_ACTIVITY_TRADE_REWARD_REQ] = new NetMsg_ActivityGetTradeReward_CS();
    this.AutoResponser[MESSAGE_ID.GET_ACTIVITIES_REQ] = new NetMsg_ActivityInfo_CS();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_ActivityInfoRep_SN();
    this.AutoResponser[MESSAGE_ID.GET_ACTIVITIES_REQ] = new NetMsg_ActivityInfoReq_CN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_ActivityRMBBuy_PUSH();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_ArenaBattleComplete();
    this.AutoResponser[MESSAGE_ID.ARENA_BUY_TICKET_REQ] = new NetMsg_ArenaBuyTicket();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_ArenaEnterRep();
    this.AutoResponser[MESSAGE_ID.ARENA_ENTER_REQ] = new NetMsg_ArenaEnterReq();
    this.AutoResponser[MESSAGE_ID.ARENA_GIVEUP_REQ] = new NetMsg_ArenaGiveUp();
    this.AutoResponser[MESSAGE_ID.ARENA_GET_REWARDS_REQ] = new NetMsg_ArenaReward();
    this.AutoResponser[MESSAGE_ID.ARENA_SELECT_CARDS_REQ] = new NetMsg_ArenaSelCard();
    this.AutoResponser[MESSAGE_ID.ARENA_SELECT_HERO_REQ] = new NetMsg_ArenaSelHero();
    this.AutoResponser[MESSAGE_ID.SET_AUTODEPLOY_REQ] = new NetMsg_BattleAutoFight_CS();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_BattleCommonError();
    this.AutoResponser[MESSAGE_ID.BATTLE_EMOJI_REQ] = new NetMsg_BattleEmoji_CN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_BattleEmoji_SN();
    this.AutoResponser[MESSAGE_ID.QUERY_EXPRESSION_SHORECUT_REQ] = new NetMsg_BattleGetEmojiList_CS();
    this.AutoResponser[MESSAGE_ID.QUIT_BATTLE_REQ] = new NetMsg_BattleQuit_CN();
    this.AutoResponser[MESSAGE_ID.BATTLE_READY_REQ] = new NetMsg_BattleReady_CN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_BattleWaiting_SN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_BPActive();
    this.AutoResponser[MESSAGE_ID.BATTLEPASS_BUY_EXP_REQ] = new NetMsg_BPBuyLevel();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_BPInfoRec();
    this.AutoResponser[MESSAGE_ID.BATTLEPASS_REQ] = new NetMsg_BPInfoReq();
    this.AutoResponser[MESSAGE_ID.BATTLEPASS_REWARD_REQ] = new NetMsg_BPLevelReward();
    this.AutoResponser[MESSAGE_ID.PVE_BUY_REQ] = new NetMsg_Buy_PVE();
    this.AutoResponser[MESSAGE_ID.CANCEL_MATCH_REQ] = new NetMsg_CancelMatch_CS();
    this.AutoResponser[MESSAGE_ID.CARD_COMPOUND_REQ] = new NetMsg_CardCompound();
    this.AutoResponser[MESSAGE_ID.CARD_RESOLVE_REQ] = new NetMsg_CardResolve();
    this.AutoResponser[MESSAGE_ID.CHALLENGE_HERO_REQ] = new NetMsg_ChallengeHero();
    this.AutoResponser[MESSAGE_ID.CHALLENGE_HERO_REQ] = new NetMsg_ChallengeHero_CN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_ChallengeHeroComplete();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_ChampBattleComplete_SN();
    this.AutoResponser[MESSAGE_ID.CHAMP_BUYTICKET_REQ] = new NetMsg_ChampBuyTicket_CS();
    this.AutoResponser[MESSAGE_ID.CHAMP_DEL_DECK_REQ] = new NetMsg_ChampDeleteDeck_CS();
    this.AutoResponser[MESSAGE_ID.CHAMP_EDIT_DECK_REQ] = new NetMsg_ChampEditDeck_CS();
    this.AutoResponser[MESSAGE_ID.CHAMP_GET_INFO_REQ] = new NetMsg_ChampGetInfo_CS();
    this.AutoResponser[MESSAGE_ID.CHAMP_GET_WINREWARD_REQ] = new NetMsg_ChampGetMatchReward_CS();
    this.AutoResponser[MESSAGE_ID.CHAMP_GET_RANKREWARD_REQ] = new NetMsg_ChampGetResultReward_CS();
    this.AutoResponser[MESSAGE_ID.CHANGE_DECK_CARDBACK_REQ] = new NetMsg_ChangeDeckCardBack();
    this.AutoResponser[MESSAGE_ID.CHANGE_DEFAULT_CARDBACK_REQ] = new NetMsg_ChangeDefaultCardBack();
    this.AutoResponser[MESSAGE_ID.CHANGE_PLAYERNAME_REQ] = new NetMsg_ChangePlayerName();
    this.AutoResponser[MESSAGE_ID.CHAT_INFO_RPT] = new NetMsg_ChatInfo_CN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_ChatInfo_SN();
    this.AutoResponser[MESSAGE_ID.CLEAR_EXPRESSION_SHORTCUT_REQ] = new NetMsg_ClearExpression_CS();
    this.AutoResponser[MESSAGE_ID.COOK_REQ] = new NetMsg_Cook();
    this.AutoResponser[MESSAGE_ID.CREATE_PVEROOM_REQ] = new NetMsg_CreatePVERoom_CN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_CreatePVERoom_SN();
    this.AutoResponser[MESSAGE_ID.DAILY_SIGNIN_REQ] = new NetMsg_DailySignIn();
    this.AutoResponser[MESSAGE_ID.DAILY_SIGNIN_REQ] = new NetMsg_DailySignIn_CN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_DailySignIn_SN();
    this.AutoResponser[MESSAGE_ID.DELETE_DECK_REQ] = new NetMsg_DeleteDeck();
    this.AutoResponser[MESSAGE_ID.DLC4_FORGING_REQ] = new NetMsg_DLC4Forging();
    this.AutoResponser[MESSAGE_ID.DLC4_GETINFO_REQ] = new NetMsg_DLC4GetInfo();
    this.AutoResponser[MESSAGE_ID.DLC4_SETEQUIPMENT_REQ] = new NetMsg_DLC4SetEquiment();
    this.AutoResponser[MESSAGE_ID.DLC4_SETTALENT_REQ] = new NetMsg_DLC4SetTAlent();
    this.AutoResponser[MESSAGE_ID.EDIT_DECK_REQ] = new NetMsg_EditDeck();
    this.AutoResponser[MESSAGE_ID.ENTER_GAME_REQ] = new NetMsg_EnterGame();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_FirstPayPush();
    this.AutoResponser[MESSAGE_ID.FIRSTCHARGEREWARD_REQ] = new NetMsg_FirstPayReward();
    this.AutoResponser[MESSAGE_ID.QUERY_FAIL_CHARGE_ORDERID_REQ] = new NetMsg_FixPay_CN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_FixPay_SN();
    this.AutoResponser[MESSAGE_ID.FRIEND_BEHAVIOR_RPT] = new NetMsg_FriendBehavior_CN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_FriendBehavior_SN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_FriendCancelMatch_SN();
    this.AutoResponser[MESSAGE_ID.FRIEND_INFO_RPT] = new NetMsg_FriendInfo_CN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_FriendInfo_SN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_FriendRefresh_SN();
    this.AutoResponser[MESSAGE_ID.FRIEND_REFRESH_SCENE_RPT] = new NetMsg_FriendRefreshScenes_CN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_FriendState_SN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_GetBattleResult();
    this.AutoResponser[MESSAGE_ID.GET_DECKCODE_REQ] = new NetMsg_GetDeckCode();
    this.AutoResponser[MESSAGE_ID.GET_DECKDATA_REQ] = new NetMsg_GetDeckData();
    this.AutoResponser[MESSAGE_ID.GET_FAVOR_REWARD_REQ] = new NetMsg_GetFavorReward();
    this.AutoResponser[MESSAGE_ID.GET_GIFTINFO_REQ] = new NetMsg_GetGiftInfo_CN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_GetGiftInfo_SN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_GetLoginActivityDataRep();
    this.AutoResponser[MESSAGE_ID.GET_LOGIN_ACTIVITY_REQ] = new NetMsg_GetLoginActivityDataReq();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_GetLoginActivityRewardRep();
    this.AutoResponser[MESSAGE_ID.GET_LOGIN_ACTIVITY_REWARD_REQ] = new NetMsg_GetLoginActivityRewardReq();
    this.AutoResponser[MESSAGE_ID.GET_QUESTION_REQ] = new NetMsg_GetQuestion();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_GetRankDetailRep();
    this.AutoResponser[MESSAGE_ID.GET_RANK_DETAIL_REQ] = new NetMsg_GetRankDetailReq();
    this.AutoResponser[MESSAGE_ID.GET_RECORDINFO_REQ] = new NetMsg_GetRecordByID();
    this.AutoResponser[MESSAGE_ID.GET_RECORDLIST_REQ] = new NetMsg_GetRecordInfo();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_GetRnakRep();
    this.AutoResponser[MESSAGE_ID.GET_RANK_REQ] = new NetMsg_GetRnakReq();
    this.AutoResponser[MESSAGE_ID.GET_SHAREDDECKS_REQ] = new NetMsg_GetShareDecks_CN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_GetShareDecks_SN();
    this.AutoResponser[MESSAGE_ID.GET_SHOP_INFO_REQ] = new NetMsg_GetShopInfo();
    this.AutoResponser[MESSAGE_ID.GET_SIGNIN_INFO_REQ] = new NetMsg_GetSignInInfo_CN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_GetSignInInfo_SN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_GildingRep();
    this.AutoResponser[MESSAGE_ID.GILDING_REQ] = new NetMsg_GildingReq();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_GildingResetRep();
    this.AutoResponser[MESSAGE_ID.GILDING_RESET_REQ] = new NetMsg_GildingResetReq();
    this.AutoResponser[MESSAGE_ID.GIVEMEFIVE_LOGIC_REQ] = new NetMsg_GMMain();
    this.AutoResponser[MESSAGE_ID.GUIDER_UPDATE_REQ] = new NetMsg_GuideRecord();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_GuideRecordRep();
    this.AutoResponser[MESSAGE_ID.HEARTBEAT_REQ] = new NetMsg_Heartbeat_CN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_Heartbeat_SN();
    this.AutoResponser[MESSAGE_ID.HERO_GIVE_GIFT_REQ] = new NetMsg_HeroGiveGift();
    this.AutoResponser[MESSAGE_ID.INFI_BUY_MESSAGE_REQ] = new NetMsg_InfiBuyClue();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_InfiEnterRep();
    this.AutoResponser[MESSAGE_ID.INFI_ENTER_REQ] = new NetMsg_InfiEnterReq();
    this.AutoResponser[MESSAGE_ID.INFI_UNLOCK_EVENT_REQ] = new NetMsg_InfiEventUnlock();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_InfiEventUnlockRMBPush();
    this.AutoResponser[MESSAGE_ID.INFI_EXIT_STAGE_REQ] = new NetMsg_InfiExitStage();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_InfiGetSimpleDataRep();
    this.AutoResponser[MESSAGE_ID.INFI_GET_SIMPLE_DATA_REQ] = new NetMsg_InfiGetSimpleDataReq();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_InfiGetStaticDataRep();
    this.AutoResponser[MESSAGE_ID.INFI_GET_STATICDATA_REQ] = new NetMsg_InfiGetStaticDataReq();
    this.AutoResponser[MESSAGE_ID.INFI_GET_STORY_REQ] = new NetMsg_InfiGetStory();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_InfiPushBattleComplete();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_InfiPushStateChange();
    this.AutoResponser[MESSAGE_ID.INFI_RECOVER_REQ] = new NetMsg_InfiRecover();
    this.AutoResponser[MESSAGE_ID.INFI_DEL_CARD_REQ] = new NetMsg_InfiRemoveCard();
    this.AutoResponser[MESSAGE_ID.INFI_DEL_SPELLEQUIP_REQ] = new NetMsg_InfiRemoveTreasure();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_InfiRoundEndPush();
    this.AutoResponser[MESSAGE_ID.INFI_SELECT_REWARD_REQ] = new NetMsg_InfiSelBattleReward();
    this.AutoResponser[MESSAGE_ID.INFI_SELECT_JOB_REQ] = new NetMsg_InfiSelClass();
    this.AutoResponser[MESSAGE_ID.INFI_SELECT_DIFFICULTY_REQ] = new NetMsg_InfiSelDifficulty();
    this.AutoResponser[MESSAGE_ID.INFI_SELECT_DECK_REQ] = new NetMsg_InfiSelectDeck();
    this.AutoResponser[MESSAGE_ID.INFI_SELECT_HERO_REQ] = new NetMsg_InfiSelectHero();
    this.AutoResponser[MESSAGE_ID.INFI_SELECT_STAGE_REQ] = new NetMsg_InfiSelectStage_CN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_InfiSelectStage_SN();
    this.AutoResponser[MESSAGE_ID.INFI_SELECT_EVENT_REQ] = new NetMsg_InfiSelEvent();
    this.AutoResponser[MESSAGE_ID.INFI_BUY_ITEM_REQ] = new NetMsg_InfiShopBuyItem();
    this.AutoResponser[MESSAGE_ID.INFI_OPEN_SHOP_BUY_REQ] = new NetMsg_InfiStartShopBuyItem();
    this.AutoResponser[MESSAGE_ID.INFI_OPENSHOP_EXIT_REQ] = new NetMsg_InfiStartShopExit();
    this.AutoResponser[MESSAGE_ID.INFI_REFRESH_OPENSHOP_REQ] = new NetMsg_InfiStartShopRefresh();
    this.AutoResponser[MESSAGE_ID.INFI_GET_BOX_REQ] = new NetMsg_InfiTakeChest();
    this.AutoResponser[MESSAGE_ID.INFI_UNLOCK_DIFFICULTY_REQ] = new NetMsg_InfiUnlockDifficulty();
    this.AutoResponser[MESSAGE_ID.INFI_UP_CARD_REQ] = new NetMsg_InfiUpCard();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_LeveUp();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_MainTownReconnect();
    this.AutoResponser[MESSAGE_ID.TASK_POINTREWARD_REQ] = new NetMsg_MissionBoxReward();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_MissionInfoRec();
    this.AutoResponser[MESSAGE_ID.TASK_DATA_REQ] = new NetMsg_MissionInfoReq();
    this.AutoResponser[MESSAGE_ID.TASK_REWARD_REQ] = new NetMsg_MissionReward();
    this.AutoResponser[MESSAGE_ID.MODIFY_EQUIP_REQ] = new NetMsg_ModifyEquip();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_NoticePush();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_Pay_SN();
    this.AutoResponser[MESSAGE_ID.PINGPONG] = new NetMsg_Ping_CN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_Ping_SN();
    this.AutoResponser[MESSAGE_ID.PULL_ACT_ACCEPT_REQ] = new NetMsg_PullActAccept();
    this.AutoResponser[MESSAGE_ID.PULL_ACT_INFO_REQ] = new NetMsg_PullActInfo();
    this.AutoResponser[MESSAGE_ID.PULL_ACT_REWARD_REQ] = new NetMsg_PullActRewardReq();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_PushHeroInfo();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_PushLadderComplete();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_PushNotice_SN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_PushPrizeInfo();
    this.AutoResponser[MESSAGE_ID.GET_ACTIVITY_PVE_INFO_REQ] = new NetMsg_PVEActivityInfo();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_PVECompletePush();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_PVEDailyInfoRep();
    this.AutoResponser[MESSAGE_ID.GET_DAILYPVEINFO_REQ] = new NetMsg_PVEDailyInfoReq();
    this.AutoResponser[MESSAGE_ID.QUERY_EXPRESSION_INFO_REQ] = new NetMsg_QueryExpressionInfo_CS();
    this.AutoResponser[MESSAGE_ID.QUERY_FRIEND_INFO_REQ] = new NetMsg_QueryFriendInfo();
    this.AutoResponser[MESSAGE_ID.QUERY_PERSONAL_INFO_REQ] = new NetMsg_QueryPersonInfoReq();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_QueryPersonInfoRsp();
    this.AutoResponser[MESSAGE_ID.QUERY_USERTITLE_INFO_REQ] = new NetMsg_QueryUserTitelInfo_CN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_QueryUserTitelInfo_SN();
    this.AutoResponser[MESSAGE_ID.RECEIVE_GIFT_REQ] = new NetMsg_ReceiveGift();
    this.AutoResponser[MESSAGE_ID.FAVOR_RECORD_REQ] = new NetMsg_RecordCollect();
    this.AutoResponser[MESSAGE_ID.DELETE_RECORD_REQ] = new NetMsg_RecordDelete();
    this.AutoResponser[MESSAGE_ID.GET_RECORDDATA_REQ] = new NetMsg_RecordPlay();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_RidingLanternNotice_SN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_RMB_PVE_SN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_RMB_ShopBuy_SN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_SeasonRewardRep();
    this.AutoResponser[MESSAGE_ID.SEASON_REWARD_REQ] = new NetMsg_SeasonRewardReq();
    this.AutoResponser[MESSAGE_ID.SET_DEFAULT_SHORTCUT_REQ] = new NetMsg_SetDefaultExpression_CS();
    this.AutoResponser[MESSAGE_ID.SET_EXPRESSION_SHORTCUT_REQ] = new NetMsg_SetExpression_CS();
    this.AutoResponser[MESSAGE_ID.SET_HEAD_INFO_REQ] = new NetMsg_SetHeadInfo_CN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_SetHeadInfo_SN();
    this.AutoResponser[MESSAGE_ID.SET_HEAD_PIC_EX_REQ] = new NetMsg_SetHeadPicExReq();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_SetHeadPicExRsp();
    this.AutoResponser[MESSAGE_ID.SET_HEAD_PIC_REQ] = new NetMsg_SetHeadPicReq();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_SetHeadPicRsp();
    this.AutoResponser[MESSAGE_ID.SET_HERO_SKIN_REQ] = new NetMsg_SetHeroSkin();
    this.AutoResponser[MESSAGE_ID.SET_PLAYERNAME_REQ] = new NetMsg_SetPlayerNameReq();
    this.AutoResponser[MESSAGE_ID.SET_USERTITLE_REQ] = new NetMsg_SetUserTitle();
    this.AutoResponser[MESSAGE_ID.SHAREDECK_REQ] = new NetMsg_ShareDeck();
    this.AutoResponser[MESSAGE_ID.SHOP_BUY_REQ] = new NetMsg_ShopBuy();
    this.AutoResponser[MESSAGE_ID.ARENA_BATTLE_REQ] = new NetMsg_StartMatchArena_CS();
    this.AutoResponser[MESSAGE_ID.CHAMP_BATTLE_REQ] = new NetMsg_StartMatchChamp_CS();
    this.AutoResponser[MESSAGE_ID.MATCH_LADDERROOM_REQ] = new NetMsg_StartMatchPVP_CS();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_Timeout_SN();
    this.AutoResponser[MESSAGE_ID.TRANS_CHAT_INFO_RPT] = new NetMsg_TransChatInfo_CN();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_TransChatInfo_SN();
    this.AutoResponser[MESSAGE_ID.SECTION_REWARD_REQ] = new NetMsg_TrialSectionReward_CS();
    this.AutoResponser[MESSAGE_ID.UNLOAD_EXPRESSION_SHORTCUT_REQ] = new NetMsg_UnloadExpressionShortcut_CS();
    this.AutoResponser[MESSAGE_ID.UPDATE_QUESTION_REQ] = new NetMsg_UpdateQuestion();
    this.AutoResponser[MESSAGE_ID.USE_ITEM_REQ] = new NetMsg_UseItem();
    this.AutoResponser[MESSAGE_ID.USE_SHAREDDECK_NT] = new NetMsg_UseSharedDeck_NT();
    this.AutoResponser[MESSAGE_ID.USE_SKIN_REQ] = new NetMsg_UseSkinReq();
    this.AutoResponser[MESSAGE_ID.NETWORK_MESSAGE_BEGIN] = new NetMsg_UseSkinRsp();
  }
}
