// 由 mc-local-share generate_ts 自动生成，请勿手改。

import { MessageControllerBase } from '../MessageControllerBase';
import { MESSAGE_ID } from 'mc-local-share';
import { NetMsg_AchieveReward_CS } from './NetMsg_AchieveReward_CS';
import { NetMsg_ActivityGetReward_CS } from './NetMsg_ActivityGetReward_CS';
import { NetMsg_ActivityGetTradeReward_CS } from './NetMsg_ActivityGetTradeReward_CS';
import { NetMsg_ActivityInfo_CS } from './NetMsg_ActivityInfo_CS';
import { NetMsg_ArenaBuyTicket } from './NetMsg_ArenaBuyTicket';
import { NetMsg_ArenaGiveUp } from './NetMsg_ArenaGiveUp';
import { NetMsg_ArenaReward } from './NetMsg_ArenaReward';
import { NetMsg_ArenaSelCard } from './NetMsg_ArenaSelCard';
import { NetMsg_ArenaSelHero } from './NetMsg_ArenaSelHero';
import { NetMsg_BattleAutoFight_CS } from './NetMsg_BattleAutoFight_CS';
import { NetMsg_BattleGetEmojiList_CS } from './NetMsg_BattleGetEmojiList_CS';
import { NetMsg_BPBuyLevel } from './NetMsg_BPBuyLevel';
import { NetMsg_BPLevelReward } from './NetMsg_BPLevelReward';
import { NetMsg_Buy_PVE } from './NetMsg_Buy_PVE';
import { NetMsg_CancelMatch_CS } from './NetMsg_CancelMatch_CS';
import { NetMsg_CardCompound } from './NetMsg_CardCompound';
import { NetMsg_CardResolve } from './NetMsg_CardResolve';
import { NetMsg_ChallengeHero } from './NetMsg_ChallengeHero';
import { NetMsg_ChampBuyTicket_CS } from './NetMsg_ChampBuyTicket_CS';
import { NetMsg_ChampDeleteDeck_CS } from './NetMsg_ChampDeleteDeck_CS';
import { NetMsg_ChampEditDeck_CS } from './NetMsg_ChampEditDeck_CS';
import { NetMsg_ChampGetInfo_CS } from './NetMsg_ChampGetInfo_CS';
import { NetMsg_ChampGetMatchReward_CS } from './NetMsg_ChampGetMatchReward_CS';
import { NetMsg_ChampGetResultReward_CS } from './NetMsg_ChampGetResultReward_CS';
import { NetMsg_ChangeDeckCardBack } from './NetMsg_ChangeDeckCardBack';
import { NetMsg_ChangeDefaultCardBack } from './NetMsg_ChangeDefaultCardBack';
import { NetMsg_ChangePlayerName } from './NetMsg_ChangePlayerName';
import { NetMsg_ClearExpression_CS } from './NetMsg_ClearExpression_CS';
import { NetMsg_Cook } from './NetMsg_Cook';
import { NetMsg_DailySignIn } from './NetMsg_DailySignIn';
import { NetMsg_DeleteDeck } from './NetMsg_DeleteDeck';
import { NetMsg_DLC4Forging } from './NetMsg_DLC4Forging';
import { NetMsg_DLC4GetInfo } from './NetMsg_DLC4GetInfo';
import { NetMsg_DLC4SetEquiment } from './NetMsg_DLC4SetEquiment';
import { NetMsg_DLC4SetTAlent } from './NetMsg_DLC4SetTAlent';
import { NetMsg_EditDeck } from './NetMsg_EditDeck';
import { NetMsg_EnterGame } from './NetMsg_EnterGame';
import { NetMsg_FirstPayReward } from './NetMsg_FirstPayReward';
import { NetMsg_GetDeckCode } from './NetMsg_GetDeckCode';
import { NetMsg_GetDeckData } from './NetMsg_GetDeckData';
import { NetMsg_GetFavorReward } from './NetMsg_GetFavorReward';
import { NetMsg_GetQuestion } from './NetMsg_GetQuestion';
import { NetMsg_GetRecordByID } from './NetMsg_GetRecordByID';
import { NetMsg_GetRecordInfo } from './NetMsg_GetRecordInfo';
import { NetMsg_GetShopInfo } from './NetMsg_GetShopInfo';
import { NetMsg_GMMain } from './NetMsg_GMMain';
import { NetMsg_HeroGiveGift } from './NetMsg_HeroGiveGift';
import { NetMsg_InfiBuyClue } from './NetMsg_InfiBuyClue';
import { NetMsg_InfiEventUnlock } from './NetMsg_InfiEventUnlock';
import { NetMsg_InfiExitStage } from './NetMsg_InfiExitStage';
import { NetMsg_InfiGetStory } from './NetMsg_InfiGetStory';
import { NetMsg_InfiRecover } from './NetMsg_InfiRecover';
import { NetMsg_InfiRemoveCard } from './NetMsg_InfiRemoveCard';
import { NetMsg_InfiRemoveTreasure } from './NetMsg_InfiRemoveTreasure';
import { NetMsg_InfiSelBattleReward } from './NetMsg_InfiSelBattleReward';
import { NetMsg_InfiSelClass } from './NetMsg_InfiSelClass';
import { NetMsg_InfiSelDifficulty } from './NetMsg_InfiSelDifficulty';
import { NetMsg_InfiSelectDeck } from './NetMsg_InfiSelectDeck';
import { NetMsg_InfiSelectHero } from './NetMsg_InfiSelectHero';
import { NetMsg_InfiSelEvent } from './NetMsg_InfiSelEvent';
import { NetMsg_InfiShopBuyItem } from './NetMsg_InfiShopBuyItem';
import { NetMsg_InfiStartShopBuyItem } from './NetMsg_InfiStartShopBuyItem';
import { NetMsg_InfiStartShopExit } from './NetMsg_InfiStartShopExit';
import { NetMsg_InfiStartShopRefresh } from './NetMsg_InfiStartShopRefresh';
import { NetMsg_InfiTakeChest } from './NetMsg_InfiTakeChest';
import { NetMsg_InfiUnlockDifficulty } from './NetMsg_InfiUnlockDifficulty';
import { NetMsg_InfiUpCard } from './NetMsg_InfiUpCard';
import { NetMsg_MissionBoxReward } from './NetMsg_MissionBoxReward';
import { NetMsg_MissionReward } from './NetMsg_MissionReward';
import { NetMsg_ModifyEquip } from './NetMsg_ModifyEquip';
import { NetMsg_PullActAccept } from './NetMsg_PullActAccept';
import { NetMsg_PullActInfo } from './NetMsg_PullActInfo';
import { NetMsg_PullActRewardReq } from './NetMsg_PullActRewardReq';
import { NetMsg_PVEActivityInfo } from './NetMsg_PVEActivityInfo';
import { NetMsg_QueryExpressionInfo_CS } from './NetMsg_QueryExpressionInfo_CS';
import { NetMsg_QueryFriendInfo } from './NetMsg_QueryFriendInfo';
import { NetMsg_ReceiveGift } from './NetMsg_ReceiveGift';
import { NetMsg_RecordCollect } from './NetMsg_RecordCollect';
import { NetMsg_RecordDelete } from './NetMsg_RecordDelete';
import { NetMsg_RecordPlay } from './NetMsg_RecordPlay';
import { NetMsg_SetDefaultExpression_CS } from './NetMsg_SetDefaultExpression_CS';
import { NetMsg_SetExpression_CS } from './NetMsg_SetExpression_CS';
import { NetMsg_SetHeroSkin } from './NetMsg_SetHeroSkin';
import { NetMsg_SetPlayerNameReq } from './NetMsg_SetPlayerNameReq';
import { NetMsg_SetUserTitle } from './NetMsg_SetUserTitle';
import { NetMsg_ShareDeck } from './NetMsg_ShareDeck';
import { NetMsg_ShopBuy } from './NetMsg_ShopBuy';
import { NetMsg_StartMatchArena_CS } from './NetMsg_StartMatchArena_CS';
import { NetMsg_StartMatchChamp_CS } from './NetMsg_StartMatchChamp_CS';
import { NetMsg_StartMatchPVP_CS } from './NetMsg_StartMatchPVP_CS';
import { NetMsg_TrialSectionReward_CS } from './NetMsg_TrialSectionReward_CS';
import { NetMsg_UnloadExpressionShortcut_CS } from './NetMsg_UnloadExpressionShortcut_CS';
import { NetMsg_UseItem } from './NetMsg_UseItem';

export class MessageController extends MessageControllerBase {
  constructor() {
    super();
    this.AutoResponser[MESSAGE_ID.GET_ACHIEVE_REWARD_REQ] = new NetMsg_AchieveReward_CS();
    this.AutoResponser[MESSAGE_ID.GET_ACTIVITY_REWARD_REQ] = new NetMsg_ActivityGetReward_CS();
    this.AutoResponser[MESSAGE_ID.GET_ACTIVITY_TRADE_REWARD_REQ] = new NetMsg_ActivityGetTradeReward_CS();
    this.AutoResponser[MESSAGE_ID.GET_ACTIVITIES_REQ] = new NetMsg_ActivityInfo_CS();
    this.AutoResponser[MESSAGE_ID.ARENA_BUY_TICKET_REQ] = new NetMsg_ArenaBuyTicket();
    this.AutoResponser[MESSAGE_ID.ARENA_GIVEUP_REQ] = new NetMsg_ArenaGiveUp();
    this.AutoResponser[MESSAGE_ID.ARENA_GET_REWARDS_REQ] = new NetMsg_ArenaReward();
    this.AutoResponser[MESSAGE_ID.ARENA_SELECT_CARDS_REQ] = new NetMsg_ArenaSelCard();
    this.AutoResponser[MESSAGE_ID.ARENA_SELECT_HERO_REQ] = new NetMsg_ArenaSelHero();
    this.AutoResponser[MESSAGE_ID.SET_AUTODEPLOY_REQ] = new NetMsg_BattleAutoFight_CS();
    this.AutoResponser[MESSAGE_ID.QUERY_EXPRESSION_SHORECUT_REQ] = new NetMsg_BattleGetEmojiList_CS();
    this.AutoResponser[MESSAGE_ID.BATTLEPASS_BUY_EXP_REQ] = new NetMsg_BPBuyLevel();
    this.AutoResponser[MESSAGE_ID.BATTLEPASS_REWARD_REQ] = new NetMsg_BPLevelReward();
    this.AutoResponser[MESSAGE_ID.PVE_BUY_REQ] = new NetMsg_Buy_PVE();
    this.AutoResponser[MESSAGE_ID.CANCEL_MATCH_REQ] = new NetMsg_CancelMatch_CS();
    this.AutoResponser[MESSAGE_ID.CARD_COMPOUND_REQ] = new NetMsg_CardCompound();
    this.AutoResponser[MESSAGE_ID.CARD_RESOLVE_REQ] = new NetMsg_CardResolve();
    this.AutoResponser[MESSAGE_ID.CHALLENGE_HERO_REQ] = new NetMsg_ChallengeHero();
    this.AutoResponser[MESSAGE_ID.CHAMP_BUYTICKET_REQ] = new NetMsg_ChampBuyTicket_CS();
    this.AutoResponser[MESSAGE_ID.CHAMP_DEL_DECK_REQ] = new NetMsg_ChampDeleteDeck_CS();
    this.AutoResponser[MESSAGE_ID.CHAMP_EDIT_DECK_REQ] = new NetMsg_ChampEditDeck_CS();
    this.AutoResponser[MESSAGE_ID.CHAMP_GET_INFO_REQ] = new NetMsg_ChampGetInfo_CS();
    this.AutoResponser[MESSAGE_ID.CHAMP_GET_WINREWARD_REQ] = new NetMsg_ChampGetMatchReward_CS();
    this.AutoResponser[MESSAGE_ID.CHAMP_GET_RANKREWARD_REQ] = new NetMsg_ChampGetResultReward_CS();
    this.AutoResponser[MESSAGE_ID.CHANGE_DECK_CARDBACK_REQ] = new NetMsg_ChangeDeckCardBack();
    this.AutoResponser[MESSAGE_ID.CHANGE_DEFAULT_CARDBACK_REQ] = new NetMsg_ChangeDefaultCardBack();
    this.AutoResponser[MESSAGE_ID.CHANGE_PLAYERNAME_REQ] = new NetMsg_ChangePlayerName();
    this.AutoResponser[MESSAGE_ID.CLEAR_EXPRESSION_SHORTCUT_REQ] = new NetMsg_ClearExpression_CS();
    this.AutoResponser[MESSAGE_ID.COOK_REQ] = new NetMsg_Cook();
    this.AutoResponser[MESSAGE_ID.DAILY_SIGNIN_REQ] = new NetMsg_DailySignIn();
    this.AutoResponser[MESSAGE_ID.DELETE_DECK_REQ] = new NetMsg_DeleteDeck();
    this.AutoResponser[MESSAGE_ID.DLC4_FORGING_REQ] = new NetMsg_DLC4Forging();
    this.AutoResponser[MESSAGE_ID.DLC4_GETINFO_REQ] = new NetMsg_DLC4GetInfo();
    this.AutoResponser[MESSAGE_ID.DLC4_SETEQUIPMENT_REQ] = new NetMsg_DLC4SetEquiment();
    this.AutoResponser[MESSAGE_ID.DLC4_SETTALENT_REQ] = new NetMsg_DLC4SetTAlent();
    this.AutoResponser[MESSAGE_ID.EDIT_DECK_REQ] = new NetMsg_EditDeck();
    this.AutoResponser[MESSAGE_ID.ENTER_GAME_REQ] = new NetMsg_EnterGame();
    this.AutoResponser[MESSAGE_ID.FIRSTCHARGEREWARD_REQ] = new NetMsg_FirstPayReward();
    this.AutoResponser[MESSAGE_ID.GET_DECKCODE_REQ] = new NetMsg_GetDeckCode();
    this.AutoResponser[MESSAGE_ID.GET_DECKDATA_REQ] = new NetMsg_GetDeckData();
    this.AutoResponser[MESSAGE_ID.GET_FAVOR_REWARD_REQ] = new NetMsg_GetFavorReward();
    this.AutoResponser[MESSAGE_ID.GET_QUESTION_REQ] = new NetMsg_GetQuestion();
    this.AutoResponser[MESSAGE_ID.GET_RECORDINFO_REQ] = new NetMsg_GetRecordByID();
    this.AutoResponser[MESSAGE_ID.GET_RECORDLIST_REQ] = new NetMsg_GetRecordInfo();
    this.AutoResponser[MESSAGE_ID.GET_SHOP_INFO_REQ] = new NetMsg_GetShopInfo();
    this.AutoResponser[MESSAGE_ID.GIVEMEFIVE_LOGIC_REQ] = new NetMsg_GMMain();
    this.AutoResponser[MESSAGE_ID.HERO_GIVE_GIFT_REQ] = new NetMsg_HeroGiveGift();
    this.AutoResponser[MESSAGE_ID.INFI_BUY_MESSAGE_REQ] = new NetMsg_InfiBuyClue();
    this.AutoResponser[MESSAGE_ID.INFI_UNLOCK_EVENT_REQ] = new NetMsg_InfiEventUnlock();
    this.AutoResponser[MESSAGE_ID.INFI_EXIT_STAGE_REQ] = new NetMsg_InfiExitStage();
    this.AutoResponser[MESSAGE_ID.INFI_GET_STORY_REQ] = new NetMsg_InfiGetStory();
    this.AutoResponser[MESSAGE_ID.INFI_RECOVER_REQ] = new NetMsg_InfiRecover();
    this.AutoResponser[MESSAGE_ID.INFI_DEL_CARD_REQ] = new NetMsg_InfiRemoveCard();
    this.AutoResponser[MESSAGE_ID.INFI_DEL_SPELLEQUIP_REQ] = new NetMsg_InfiRemoveTreasure();
    this.AutoResponser[MESSAGE_ID.INFI_SELECT_REWARD_REQ] = new NetMsg_InfiSelBattleReward();
    this.AutoResponser[MESSAGE_ID.INFI_SELECT_JOB_REQ] = new NetMsg_InfiSelClass();
    this.AutoResponser[MESSAGE_ID.INFI_SELECT_DIFFICULTY_REQ] = new NetMsg_InfiSelDifficulty();
    this.AutoResponser[MESSAGE_ID.INFI_SELECT_DECK_REQ] = new NetMsg_InfiSelectDeck();
    this.AutoResponser[MESSAGE_ID.INFI_SELECT_HERO_REQ] = new NetMsg_InfiSelectHero();
    this.AutoResponser[MESSAGE_ID.INFI_SELECT_EVENT_REQ] = new NetMsg_InfiSelEvent();
    this.AutoResponser[MESSAGE_ID.INFI_BUY_ITEM_REQ] = new NetMsg_InfiShopBuyItem();
    this.AutoResponser[MESSAGE_ID.INFI_OPEN_SHOP_BUY_REQ] = new NetMsg_InfiStartShopBuyItem();
    this.AutoResponser[MESSAGE_ID.INFI_OPENSHOP_EXIT_REQ] = new NetMsg_InfiStartShopExit();
    this.AutoResponser[MESSAGE_ID.INFI_REFRESH_OPENSHOP_REQ] = new NetMsg_InfiStartShopRefresh();
    this.AutoResponser[MESSAGE_ID.INFI_GET_BOX_REQ] = new NetMsg_InfiTakeChest();
    this.AutoResponser[MESSAGE_ID.INFI_UNLOCK_DIFFICULTY_REQ] = new NetMsg_InfiUnlockDifficulty();
    this.AutoResponser[MESSAGE_ID.INFI_UP_CARD_REQ] = new NetMsg_InfiUpCard();
    this.AutoResponser[MESSAGE_ID.TASK_POINTREWARD_REQ] = new NetMsg_MissionBoxReward();
    this.AutoResponser[MESSAGE_ID.TASK_REWARD_REQ] = new NetMsg_MissionReward();
    this.AutoResponser[MESSAGE_ID.MODIFY_EQUIP_REQ] = new NetMsg_ModifyEquip();
    this.AutoResponser[MESSAGE_ID.PULL_ACT_ACCEPT_REQ] = new NetMsg_PullActAccept();
    this.AutoResponser[MESSAGE_ID.PULL_ACT_INFO_REQ] = new NetMsg_PullActInfo();
    this.AutoResponser[MESSAGE_ID.PULL_ACT_REWARD_REQ] = new NetMsg_PullActRewardReq();
    this.AutoResponser[MESSAGE_ID.GET_ACTIVITY_PVE_INFO_REQ] = new NetMsg_PVEActivityInfo();
    this.AutoResponser[MESSAGE_ID.QUERY_EXPRESSION_INFO_REQ] = new NetMsg_QueryExpressionInfo_CS();
    this.AutoResponser[MESSAGE_ID.QUERY_FRIEND_INFO_REQ] = new NetMsg_QueryFriendInfo();
    this.AutoResponser[MESSAGE_ID.RECEIVE_GIFT_REQ] = new NetMsg_ReceiveGift();
    this.AutoResponser[MESSAGE_ID.FAVOR_RECORD_REQ] = new NetMsg_RecordCollect();
    this.AutoResponser[MESSAGE_ID.DELETE_RECORD_REQ] = new NetMsg_RecordDelete();
    this.AutoResponser[MESSAGE_ID.GET_RECORDDATA_REQ] = new NetMsg_RecordPlay();
    this.AutoResponser[MESSAGE_ID.SET_DEFAULT_SHORTCUT_REQ] = new NetMsg_SetDefaultExpression_CS();
    this.AutoResponser[MESSAGE_ID.SET_EXPRESSION_SHORTCUT_REQ] = new NetMsg_SetExpression_CS();
    this.AutoResponser[MESSAGE_ID.SET_HERO_SKIN_REQ] = new NetMsg_SetHeroSkin();
    this.AutoResponser[MESSAGE_ID.SET_PLAYERNAME_REQ] = new NetMsg_SetPlayerNameReq();
    this.AutoResponser[MESSAGE_ID.SET_USERTITLE_REQ] = new NetMsg_SetUserTitle();
    this.AutoResponser[MESSAGE_ID.SHAREDECK_REQ] = new NetMsg_ShareDeck();
    this.AutoResponser[MESSAGE_ID.SHOP_BUY_REQ] = new NetMsg_ShopBuy();
    this.AutoResponser[MESSAGE_ID.ARENA_BATTLE_REQ] = new NetMsg_StartMatchArena_CS();
    this.AutoResponser[MESSAGE_ID.CHAMP_BATTLE_REQ] = new NetMsg_StartMatchChamp_CS();
    this.AutoResponser[MESSAGE_ID.MATCH_LADDERROOM_REQ] = new NetMsg_StartMatchPVP_CS();
    this.AutoResponser[MESSAGE_ID.SECTION_REWARD_REQ] = new NetMsg_TrialSectionReward_CS();
    this.AutoResponser[MESSAGE_ID.UNLOAD_EXPRESSION_SHORTCUT_REQ] = new NetMsg_UnloadExpressionShortcut_CS();
    this.AutoResponser[MESSAGE_ID.USE_ITEM_REQ] = new NetMsg_UseItem();
  }
}
