// 由 mc-local-share gen 自动生成，请勿手改。

export enum ErrorCode {
  SUCCESS = 0,
  ERROR = -1,
  VERSION_ERROR = -100,
  UP_PARAM_ERROR = -101,
  TRY_AGAIN_LATER = -102,
  BAND_MESSAGE = -103,
  SERVICE_NOT_READY = -104,
  SERVICE_EXCEPTION = -105,
  SESSION_NOT_FIND = -106,
  ACCOUNT_EXISTS = -300,
  ACCOUNT_NOT_EXISTS = -301,
  PASSWORD_ERROR = -302,
  BAND = -303,
  SDK_ERROR = -304,
  LOGIN_LIMIT = -305,
  LOGIN_CLOSE = -306,
  ACTIVATIONCODE_NEED = -307,
  ACTIVATIONCODE_USED = -308,
  ACTIVATIONCODE_ERROR = -309,
  NICKNAME_EXIST = -310,
  LOGIN_ELSEWHERE = -311,
  KICKOUT_BYGM = -312,
  REAL_NAME_NOTSET = -313,
  ANTI_ADDICTION_TIME = -314,
  ANTI_ADDICTION_LIMIT = -315,
  ANTI_ADDICTION_LIMIT_HOLIDAY = -316,
  KICKOUT_ANTI = -317,
  NICKNAME_ILLEGAL = -318,
  CONFIG_ERROR = -500,
  HERO_DEFINE = -501,
  SKILL_DEFINE = -502,
  CARD_DEFINE = -503,
  EQUIP_DEFINE = -504,
  REWARD_DEFINE = -505,
  STAGE_DEFINE = -506,
  RECIPE_DEFINE = -507,
  INFI_DIFFICULTY_DEFINE = -508,
  ITEM_DEFINE = -509,
  INFI_BEGIN_PRICES_DEFINE = -510,
  INFI_BEGIN_REFRESH_DEFINE = -511,
  TREASURE_DEFINE = -512,
  RPG_LEVEL_DEFINE = -513,
  ARENA_COMBINATION_DEFINE = -514,
  INFI_CLASS_INIT_DEFINE = -515,
  HERO_SKIN_DEFINE = -516,
  CARD_NOT_ENOUGH = -700,
  CARD_SAME_COUNT_LIMIT = -701,
  DECK_CARDS_COUNT_LIMIT = -702,
  DECK_SET_INVALID = -703,
  DECK_COUNT_LIMIT = -704,
  DECK_NOT_FIND = -705,
  PVP_CANNOT_SET_EQUIP = -706,
  CARD_RESOLVE_PART_ERROR = -707,
  CARD_NOT_FIND = -708,
  CARD_UP_COUNT_LIMIT = -709,
  CARD_DEL_COUNT_LIMIT = -710,
  CARD_NEXT_LEVEL_NOT_FIND = -711,
  CARD_CANNOT_COMPOUND = -712,
  HERO_JOB_NOTMATCH = -714,
  HERO_SKILL_NOTMATCH = -715,
  CARD_JOB_NOTMATCH = -716,
  DECK_HERO_INVALID = -717,
  DECK_JOB_INVALID = -718,
  DECK_SKILL_INVALID = -719,
  CARDBACK_LIMIT = -720,
  CANNOT_SHARE_DECK = -721,
  DECK_SHARED = -722,
  CARD_NOT_FORMAL = -723,
  HERO_LOCKED = -1000,
  HERO_NOT_FIND = -1001,
  JOB_NOT_FIND = -1002,
  HERO_STATE_ERROR = -1003,
  EQUIP_SLOT_LOCKED = -1200,
  EQUIP_SAME = -1201,
  EQUIP_JOB_LIMIT = -1202,
  EQUIP_LEVEL_LIMIT = -1203,
  EQUIP_NOT_FIND = -1204,
  ACHIEVEMENT_NOT_REACH = -1400,
  ACHIEVEMENT_REWARD = -1401,
  BATTLEPASS_NOT_REACH = -1500,
  MONEY_NOT_ENOUGH = -1600,
  ITEM_NOT_ENOUGH = -1601,
  ITEM_NOT_FIND = -1602,
  ITEM_HERO_LIMIT = -1603,
  ITEM_COUNT_LIMIT = -1604,
  ITEM_ARENATICKET = -1605,
  WRONG_ITEM_TYPE = -1606,
  ACTIVITY_NOT_REACH = -1900,
  ACTIVITY_REWARD = -1901,
  ACTIVITY_NOT_OPEN = -1902,
  ACTIVITY_REWARD_EXPIRE = -1903,
  PUSH_ACT_CODE_ERROR = -1950,
  PUSH_ACT_LEVEL_LIMIT = -1951,
  PUSH_ACT_COUNT_LIMIT = -1952,
  PUSH_ACT_NOT_REACH = -1953,
  PUSH_ACT_REWARD_COMPLETE = -1954,
  PUSH_ACT_ALREADY_ACCEPT = -1955,
  TASK_NOT_EXIST = -2000,
  TASK_DATA_EXPIRED = -2001,
  TASK_NOT_REACH = -2002,
  TASK_REWARD = -2003,
  LADDER_SEASON_NOT_FIND = -2100,
  SEASON_NOT_REACH = -2101,
  PVE_ORDER_ERROR = -2200,
  PVE_STAGE_LOCK = -2201,
  WRONG_STAGE_TYPE = -2202,
  CHAPTER_NOT_REACH = -2203,
  SECTION_NOT_REACH = -2204,
  PVE_NOT_BUY = -2205,
  PVE_ALREADY_BUY = -2206,
  STAGE_LIMIT = -2207,
  BATTLE_NOT_EXIST = -2300,
  BATTLE_READY_REPEAT = -2301,
  BATTLE_NOT_READY = -2302,
  BATTLE_NOT_END = -2303,
  BATTLE_CANNOT_CHANGECARD = -2304,
  BATTLE_CANNOT_DEPLOY = -2305,
  EMOJI_NOT_EXIST = -2306,
  EMOJI_TOO_OFTEN = -2307,
  RECORD_NOT_FOUND = -2308,
  FAVOR_RECORD_LIMIT = -2309,
  FAVOR_DONE = -2310,
  RECORD_EXPIRED = -2311,
  SHOP_BUYCOUNT_LIMIT = -2900,
  SHOP_HERO_ALREADY_GET = -2901,
  SHOP_NOT_OPEN = -2902,
  CANNOT_EQUIP_OTHER_TREASURE = -3100,
  CANNOT_EQUIP_SAME_COLOR = -3101,
  INFI_DECK_NOT_FULL = -3102,
  INFI_UNLOCK_DIFF_ORDER = -3103,
  INFI_MESSAGE_ALREADY_GET = -3104,
  INFI_DIFFICULTY_UNLOCK = -3105,
  INFI_SHOP_ITEM_SOLD = -3106,
  INFI_OPENSHOP_BUY_LIMIT = -3107,
  INFI_CARDS_COUNT_LIMIT = -3108,
  INFI_STATE_ERROR = -3109,
  INFI_BATTLEREWARD_NOT_FIND = -3110,
  INFI_BATTLEREWARD_CLAIMED = -3111,
  INFI_JOB_LOCK = -3112,
  INFI_UNLOCK_DIFF_NOT_PASS = -3113,
  INFI_EVENT_ALREADY_BUY = -3114,
  INFI_PRE_EVENT_BUY_LIMIT = -3115,
  INFI_JOB_DECK_NOT_MATCH = -3116,
  INFI_DECK_LOCK = -3117,
  MAIL_CANNOT_FIND = -3300,
  MAIL_EXPIRED = -3301,
  FAVOR_GIVE_GIFT_COUNT_LIMIT = -3400,
  FAVOR_LV_LOCK = -3401,
  FAVOR_CHALLENGE = -3402,
  FAVOR_REWARD = -3403,
  RECIPE_NOT_FIND = -3500,
  RECIPE_BUFF_EXIST = -3501,
  RECIPE_FORMAT = -3502,
  ARENA_STATE_ERROR = -3600,
  ARENA_ROUND_ERROR = -3601,
  ARENA_NOT_OPEN = -3602,
  ARENA_SELECT_CARD_ERROR = -3603,
  ARENA_GOLD_NOT_ENOUGH = -3604,
  ARENA_COUPON_NOT_ENOUGH = -3605,
  LOADINGEQUIPMENT_FAILED = -4000,
  SETEXPEDITION_FAILED = -4001,
  STORY_ORDER_ERROR = -4002,
  BUILD_CARDS_ERROR = -4003,
  PVE_CHAPTER_NOT_START = -4010,
  PVE_STAGE_NOT_FIND = -4011,
  CHAMP_NOT_OPEN = -4050,
  CHAMP_STATE_ERROR = -4051,
  CHAMP_LV_LIMIT = -4052,
  CHAMP_LADDERLV_LIMIT = -4053,
  CHAMP_ID_ROUND_ERROR = -4054,
  CHAMP_REWARD_NOT_REACH = -4055,
  CHAMP_REWARD_ALREADY_GET = -4056,
  CHAMP_RULE_ERROR = -4057,
  GIFTCODE_INVALID = -5000,
  GIFTCODE_USED = -5001,
  NAME_LENGTH_LIMIT = -5002,
  OPTION_INDEX_ERROR = -5005,
  RECOVER_COUNT_LIMIT = -5006,
  SIGNIN_COUNT_LIMIT = -5007,
  BUY_COUNT_LIMIT = -5008,
  STAGE_ERROR = -5009,
  WAIT_MATCHINFO = -5010,
  SAME_TYPE_GIFTCODE_USED = -5011,
  HEAD_PIC_NOT_HAVE = -5012,
  HEAD_PICEX_NOT_HAVE = -5013,
  EXPRESSION_NOT_HAVE = -5014,
  EXPRESSION_SET = -5015,
  EXPRESSION_HAVE = -5016,
  USERTITLE_NOT_HAVE = -5017,
  BACKGROUND_NOT_HAVE = -5018,
  EXPRESSION_NOT_SET = -5019,
  EXCHANGE_ERROR = -5020,
  SAME_TITLE_ID = -5021,
  GOODS_HAVE = -5022,
  SKIN_NOT_HAVE = -5023,
  SKIN_HAVE = -5024,
  CHANGE_NAME_CD = -5025,
  DLC4_CHARACTER_UNLOCK = -6000,
  DLC4_TALENT_HERO = -6001,
  DLC4_TALENT_UNLOCK = -6002,
  DLC4_EQUIP_HERO = -6003,
  DLC4_EQUIP_UNLOCK = -6004,
  DLC4_EQUIP_EXISTS = -6005,
  DLC4_STAR_NOT_ENOUGH = -6006,
  DLC4_SEASONPASS_PURCHASED = -6007,
}

export enum ActionType {
  PUT = 1,
  PUSH = 2,
  SKILL = 3,
  ATTACK = 4,
}

export enum AttackType {
  Born = 0,
  Attack = 1,
  DualAttack = 2,
  AttackFace = 3,
  Skill = 4,
  Dead = 5,
  Deal = 6,
  Disappear = 7,
  Appear = 8,
  ChangeStatus = 9,
  GetCard = 10,
  FieldWarn = 11,
  ChangeHandCost = 12,
  DealStep = 13,
  RoundBeginStep = 14,
  RoundFightStep = 15,
  RoundEndStep = 16,
  BattleResult = 17,
  Discard = 18,
  ChangeHero = 19,
  Talk = 20,
  ChangeStatusAddBuff = 21,
  ChangeMana = 22,
  ExplanChange = 23,
  FlyAttack = 24,
  HandDisappear = 25,
  Deform = 26,
  GetCardClearly = 27,
  HandAppear = 28,
  DisappearByHuge = 29,
  AppearByHuge = 30,
  ChangeLocation = 31,
}

export enum LocationStatus {
  DEFAULT_LOCATION_STATUS = 0,
  LEAVE_DECK = 1,
  LEAVE_HAND = 2,
  LEAVE_FIELD = 3,
  LEAVE_CEMETERY = 4,
  ENTER_DECK = 5,
  ENTER_HAND = 6,
  ENTER_FIELD = 7,
  ENTER_CEMETERY = 8,
  DECK_TO_HAND = 9,
  DECK_TO_FIELD = 10,
  DECK_TO_CEMETERY = 11,
  HAND_TO_DECK = 12,
  HAND_TO_FIELD = 13,
  HAND_TO_CEMETERY = 14,
  FIELD_TO_DECK = 15,
  FIELD_TO_HAND = 16,
  FIELD_TO_CEMETERY = 17,
  CEMETERY_TO_DECK = 18,
  CEMETERY_TO_HAND = 19,
  CEMETERY_TO_FIELD = 20,
}

export enum BattleLogType {
  NullType = 0,
  PlayGame = 1,
  RoundEnter = 2,
  RoundBegin = 3,
  RoundFight = 4,
  RoundEnd = 5,
  ActiveSkill = 6,
  HeroActiveSkill = 7,
  HandActiveSkill = 8,
  PassiveSkill = 9,
  HeroPassiveSkill = 10,
  HandPassiveSkill = 11,
  ChangeHeroAndHeroSkill = 12,
  DisplayDeploymentHeroSkill = 13,
  DisplaySkillSummon = 14,
  DisplayAppear = 15,
  DisplayDisappear = 16,
  DisplayGetCard = 17,
  DisplayHandThrow = 18,
  DisplayAddToDeck = 19,
  DisplayRemoveFromDeck = 20,
  DisplayAddToCemetery = 21,
  DisplayRemoveFromCemetery = 22,
  DisplayFatigue = 23,
  DisplayAddBuffer = 24,
  DisplayDeform = 25,
  DisplayMove = 26,
  DisplayDevour = 27,
  DisplayHeal = 28,
  HeroHeal = 29,
  DisplayHurt = 30,
  HeroHurt = 31,
  AssaultAttack = 32,
  CollideAttack = 33,
  CollideAttackHero = 34,
  DisplayBorn = 35,
  DisplayHeroSkill = 36,
  FieldWarn = 37,
  Snapshot1 = 38,
  Snapshot2 = 39,
}

export enum BattleLogSide {
  NullSide = 0,
  SideA = 1,
  SideB = 2,
}

export enum StepType {
  NOT_CHANGE = 0,
  BEFORE_CHANGE_CARD = 1,
  AFTER_CHANGE_CARD = 2,
  BEFORE_DEPLOYMENT = 3,
  AFTER_DEPLOYMENT = 4,
  SHOW = 5,
  END = 6,
}

export enum EArenaState {
  INVALID = -1,
  Ticket = 0,
  SelectHero = 1,
  SelectCards = 2,
  Battle = 3,
  Reward = 4,
  End = 5,
}

export enum EInfiState {
  TInvalid = -1,
  TBegin = 0,
  TSelectJob = 1,
  TSelectHero = 2,
  TSelectDifficulty = 3,
  TShop = 4,
  TMap = 5,
  TSelectDeckGroup = 10,
}

export enum RoomType {
  NULL = 0,
  PVE_ROOM = 1,
  LADDER_ROOM = 2,
  ARENA_ROOM = 3,
  INFI_ROOM = 4,
  RPG_ROOM = 5,
  FAVOR_ROOM = 6,
  FRIENDLY_ROOM = 7,
  LADDERCOMPARE_ROOM = 8,
  CHAMP_ROOM = 9,
}

export enum ETaskState {
  Not = 0,
  Complete = 1,
}

export enum EClickType {
  SKIP = 0,
  BP = 1,
  MAX = 2,
}

export enum ModuleFlagType {
  ActivityFlag = 0,
  AchievementFlag = 1,
  TaskFlag = 2,
  FavorFlag = 3,
  BattlePassFlag = 4,
  FriendAdd = 5,
  ArenaFlag = 6,
  MailFlag = 7,
  ExpressionFlag = 8,
  UserTitleFlag = 9,
  DailyPveFlag = 10,
  SkinFlag = 11,
  ModuleFlagMax = 12,
}

export enum EInfiStageType {
  Begin = 0,
  Monster = 1,
  Elites = 2,
  Boss = 3,
  Event = 4,
  Shop = 5,
  Inn = 6,
  Box = 7,
}

export enum InfiScoreState {
  Default = 0,
  MonthHighest = 1,
  HistoryHighest = 2,
}

export enum InfiSelectRewardType {
  Giveup = -1,
  Silver = 0,
  Card = 1,
  Treasure = 2,
}

export enum ActivityStatus {
  Open = 0,
  Extend = 1,
  Close = 2,
}

export enum EFriendBehaviorOp {
  Add = 1,
  AgreeAdd = 2,
  DenyAdd = 3,
  Combat = 4,
  AgreeCombat = 5,
  DenyCombat = 6,
  CancelCombat = 7,
  Search = 8,
  Del = 9,
  ReadyCombat = 10,
  FinishCombat = 11,
  CancelReady = 12,
  Busy = 13,
  RefreshSearchPlayer = 14,
  OverTimeCancelCombat = 15,
  AllAdd = 16,
  AllCancel = 17,
  QueryCombat = 18,
  QueryCombatExist = 19,
  ErrFriendListFull = 20,
  ErrFriendList = 21,
  SendAddSuccess = 22,
  ErrNotExist = 23,
  ErrUFID = 24,
  ErrAlreadyFriend = 25,
  ErrNotFriend = 26,
  AddSuccess = 27,
  SendCombatSuccess = 28,
  ErrBusy = 29,
  DenySuccess = 30,
  CancelCombatSuccess = 31,
  ErrFriendInviteFull = 32,
}

export enum EFriendState {
  stOffline = 0,
  stOnline = 1,
  stBattle = 2,
  stBusy = 3,
  stVedio = 4,
}

export enum FriendSceneState {
  Friend_Scene_In_Lobby = 1,
  Friend_Scene_NOT_In_Lobby = 2,
  Friend_Scene_Look_Vedio = 3,
}

export enum ChatType {
  secret = 1,
  friend = 2,
  guild = 3,
  world = 4,
}

export enum ContentType {
  CONTENT_TYPE_CHAT = 0,
  CONTENT_TYPE_LADDERCOMPARE = 1,
}

export enum CostType {
  Normal = 0,
  Transfer = 1,
}
